export const SCHOLARS_FETCH_STARTED = 'SCHOLARS_FETCH_STARTED';
export const SCHOLARS_FETCH_COMPLETED = 'SCHOLARS_FETCH_COMPLETED';
export const SCHOLARS_FETCH_FAILED = 'SCHOLARS_FETCH_FAILED';
export const SCHOLAR_ADD_STARTED = 'SCHOLAR_ADD_STARTED';
export const SCHOLAR_ADD_COMPLETED = 'SCHOLAR_ADD_COMPLETED';
export const SCHOLAR_ADD_FAILED = 'SCHOLAR_ADD_FAILED';
export const SET_SCHOLAR_STATUS = 'SET_SCHOLAR_STATUS';