
export const ASSISTANCE_CLUB_FETCH_STARTED = 'ASSISTANCE_CLUB_FETCH_STARTED';
export const ASSISTANCE_CLUB_FETCH_COMPLETED = 'ASSISTANCE_CLUB_FETCH_COMPLETED';
export const ASSISTANCE_CLUB_FETCH_FAILED = 'ASSISTANCE_CLUB_FETCH_FAILED';

export const ASSISTANCE_CLUBS_FETCH_STARTED = 'ASSISTANCE_CLUBS_FETCH_STARTED';
export const ASSISTANCE_CLUBS_FETCH_COMPLETED = 'ASSISTANCE_CLUBS_FETCH_COMPLETED';
export const ASSISTANCE_CLUBS_FETCH_FAILED = 'ASSISTANCE_CLUBS_FETCH_FAILED';

export const PLAYERS_FETCH_STARTED = 'PLAYERS_FETCH_STARTED';
export const PLAYERS_FETCH_COMPLETED = 'PLAYERS_FETCH_COMPLETED';
export const PLAYERS_FETCH_FAILED = 'PLAYERS_FETCH_FAILED';

export const PLAYERS_SPORT_FETCH_STARTED = 'PLAYERS_SPORT_FETCH_STARTED';
export const PLAYERS_SPORT_FETCH_COMPLETED = 'PLAYERS_SPORT_FETCH_COMPLETED';
export const PLAYERS_SPORT_FETCH_FAILED = 'PLAYERS_SPORT_FETCH_FAILED';

export const TEAMST_FETCH_STARTED = 'TEAMST_FETCH_STARTED';
export const TEAMST_FETCH_COMPLETED = 'TEAMST_FETCH_COMPLETED';
export const TEAMST_FETCH_FAILED = 'TEAMST_FETCH_FAILED';

export const TEAMST_SPORT_FETCH_STARTED = 'TEAMST_SPORT_FETCH_STARTED';
export const TEAMST_SPORT_FETCH_COMPLETED = 'TEAMST_SPORT_FETCH_COMPLETED';
export const TEAMST_SPORT_FETCH_FAILED = 'TEAMST_SPORT_FETCH_FAILED';

export const GENDERT_FETCH_STARTED = 'GENDERT_FETCH_STARTED';
export const GENDERT_FETCH_COMPLETED = 'GENDERT_FETCH_COMPLETED';
export const GENDERT_FETCH_FAILED = 'GENDERT_FETCH_FAILED';

export const GENDERT_SPORT_FETCH_STARTED = 'GENDERT_SPORT_FETCH_STARTED';
export const GENDERT_SPORT_FETCH_COMPLETED = 'GENDERT_SPORT_FETCH_COMPLETED';
export const GENDERT_SPORT_FETCH_FAILED = 'GENDERT_SPORT_FETCH_FAILED';

export const SCHOLARSS_FETCH_STARTED = 'SCHOLARSS_FETCH_STARTED';
export const SCHOLARSS_FETCH_COMPLETED = 'SCHOLARSS_FETCH_COMPLETED';
export const SCHOLARSS_FETCH_FAILED = 'SCHOLARSS_FETCH_FAILED';

export const PARTICIPATIONWK_TIME_FETCH_STARTED = 'PARTICIPATIONWK_TIME_FETCH_STARTED';
export const PARTICIPATIONWK_TIME_FETCH_COMPLETED = 'PARTICIPATIONWK_TIME_FETCH_COMPLETED';
export const PARTICIPATIONWK_TIME_FETCH_FAILED = 'PARTICIPATIONWK_TIME_FETCH_FAILED';

export const PARTICIPATIONWK_FETCH_STARTED = 'PARTICIPATIONWK_FETCH_STARTED';
export const PARTICIPATIONWK_FETCH_COMPLETED = 'PARTICIPATIONWK_FETCH_COMPLETED';
export const PARTICIPATIONWK_FETCH_FAILED = 'PARTICIPATIONWK_FETCH_FAILED';

export const PARTICIPATIONWK_TIME_G_FETCH_STARTED = 'PARTICIPATIONWK_TIME_G_FETCH_STARTED';
export const PARTICIPATIONWK_TIME_G_FETCH_COMPLETED = 'PARTICIPATIONWK_TIME_G_FETCH_COMPLETED';
export const PARTICIPATIONWK_TIME_G_FETCH_FAILED = 'PARTICIPATIONWK_TIME_G_FETCH_FAILED';

export const PARTICIPATIONWK_G_FETCH_STARTED = 'PARTICIPATIONWK_G_FETCH_STARTED';
export const PARTICIPATIONWK_G_FETCH_COMPLETED = 'PARTICIPATIONWK_G_FETCH_COMPLETED';
export const PARTICIPATIONWK_G_FETCH_FAILED = 'PARTICIPATIONWK_G_FETCH_FAILED';