
export const ASSISTANCE_CLUB_FETCH_STARTED = 'ASSISTANCE_CLUB_FETCH_STARTED';
export const ASSISTANCE_CLUB_FETCH_COMPLETED = 'ASSISTANCE_CLUB_FETCH_COMPLETED';
export const ASSISTANCE_CLUB_FETCH_FAILED = 'ASSISTANCE_CLUB_FETCH_FAILED';

export const ASSISTANCE_CLUBS_FETCH_STARTED = 'ASSISTANCE_CLUBS_FETCH_STARTED';
export const ASSISTANCE_CLUBS_FETCH_COMPLETED = 'ASSISTANCE_CLUBS_FETCH_COMPLETED';
export const ASSISTANCE_CLUBS_FETCH_FAILED = 'ASSISTANCE_CLUBS_FETCH_FAILED';

export const PLAYERS_FETCH_STARTED = 'PLAYERS_FETCH_STARTED';
export const PLAYERS_FETCH_COMPLETED = 'PLAYERS_FETCH_COMPLETED';
export const PLAYERS_FETCH_FAILED = 'PLAYERS_FETCH_FAILED';

export const PLAYERS_SPORT_FETCH_STARTED = 'PLAYERS_SPORT_FETCH_STARTED';
export const PLAYERS_SPORT_FETCH_COMPLETED = 'PLAYERS_SPORT_FETCH_COMPLETED';
export const PLAYERS_SPORT_FETCH_FAILED = 'PLAYERS_SPORT_FETCH_FAILED';

export const TEAMST_FETCH_STARTED = 'TEAMST_FETCH_STARTED';
export const TEAMST_FETCH_COMPLETED = 'TEAMST_FETCH_COMPLETED';
export const TEAMST_FETCH_FAILED = 'TEAMST_FETCH_FAILED';

export const TEAMST_SPORT_FETCH_STARTED = 'TEAMST_SPORT_FETCH_STARTED';
export const TEAMST_SPORT_FETCH_COMPLETED = 'TEAMST_SPORT_FETCH_COMPLETED';
export const TEAMST_SPORT_FETCH_FAILED = 'TEAMST_SPORT_FETCH_FAILED';

export const GENDERT_FETCH_STARTED = 'GENDERT_FETCH_STARTED';
export const GENDERT_FETCH_COMPLETED = 'GENDERT_FETCH_COMPLETED';
export const GENDERT_FETCH_FAILED = 'GENDERT_FETCH_FAILED';

export const GENDERT_SPORT_FETCH_STARTED = 'GENDERT_SPORT_FETCH_STARTED';
export const GENDERT_SPORT_FETCH_COMPLETED = 'GENDERT_SPORT_FETCH_COMPLETED';
export const GENDERT_SPORT_FETCH_FAILED = 'GENDERT_SPORT_FETCH_FAILED';

export const SCHOLARSS_FETCH_STARTED = 'SCHOLARSS_FETCH_STARTED';
export const SCHOLARSS_FETCH_COMPLETED = 'SCHOLARSS_FETCH_COMPLETED';
export const SCHOLARSS_FETCH_FAILED = 'SCHOLARSS_FETCH_FAILED';

export const PARTICIPATIONWK_TIME_FETCH_STARTED = 'PARTICIPATIONWK_TIME_FETCH_STARTED';
export const PARTICIPATIONWK_TIME_FETCH_COMPLETED = 'PARTICIPATIONWK_TIME_FETCH_COMPLETED';
export const PARTICIPATIONWK_TIME_FETCH_FAILED = 'PARTICIPATIONWK_TIME_FETCH_FAILED';

export const PARTICIPATIONWK_FETCH_STARTED = 'PARTICIPATIONWK_FETCH_STARTED';
export const PARTICIPATIONWK_FETCH_COMPLETED = 'PARTICIPATIONWK_FETCH_COMPLETED';
export const PARTICIPATIONWK_FETCH_FAILED = 'PARTICIPATIONWK_FETCH_FAILED';

export const PARTICIPATIONWK_TIME_G_FETCH_STARTED = 'PARTICIPATIONWK_TIME_G_FETCH_STARTED';
export const PARTICIPATIONWK_TIME_G_FETCH_COMPLETED = 'PARTICIPATIONWK_TIME_G_FETCH_COMPLETED';
export const PARTICIPATIONWK_TIME_G_FETCH_FAILED = 'PARTICIPATIONWK_TIME_G_FETCH_FAILED';

export const PARTICIPATIONWK_G_FETCH_STARTED = 'PARTICIPATIONWK_G_FETCH_STARTED';
export const PARTICIPATIONWK_G_FETCH_COMPLETED = 'PARTICIPATIONWK_G_FETCH_COMPLETED';
export const PARTICIPATIONWK_G_FETCH_FAILED = 'PARTICIPATIONWK_G_FETCH_FAILED';

export const FEMALE_SCHOLARS_FETCH_STARTED = 'FEMALE_SCHOLARS_FETCH_STARTED';
export const FEMALE_SCHOLARS_FETCH_COMPLETED = 'FEMALE_SCHOLARS_FETCH_COMPLETED';
export const FEMALE_SCHOLARS_FETCH_FAILED = 'FEMALE_SCHOLARS_FETCH_FAILED';

export const MALE_SCHOLARS_FETCH_STARTED = 'MALE_SCHOLARS_FETCH_STARTED';
export const MALE_SCHOLARS_FETCH_COMPLETED = 'MALE_SCHOLARS_FETCH_COMPLETED';
export const MALE_SCHOLARS_FETCH_FAILED = 'MALE_SCHOLARS_FETCH_FAILED';

export const COUNT_EVENTS_FETCH_STARTED = 'COUNT_EVENTS_FETCH_STARTED';
export const COUNT_EVENTS_FETCH_COMPLETED = 'COUNT_EVENTS_FETCH_COMPLETED';
export const COUNT_EVENTS_FETCH_FAILED = 'COUNT_EVENTS_FETCH_FAILED';

export const MALE_USERS_FETCH_STARTED = 'MALE_USERS_FETCH_STARTED';
export const MALE_USERS_FETCH_COMPLETED = 'MALE_USERS_FETCH_COMPLETED';
export const MALE_USERS_FETCH_FAILED = 'MALE_USERS_FETCH_FAILED';

export const FEMALE_USERS_FETCH_STARTED = 'FEMALE_USERS_FETCH_STARTED';
export const FEMALE_USERS_FETCH_COMPLETED = 'FEMALE_USERS_FETCH_COMPLETED';
export const FEMALE_USERS_FETCH_FAILED = 'FEMALE_USERS_FETCH_FAILED';

export const USERS_FACULTY_FETCH_STARTED = 'USERS_FACULTY_FETCH_STARTED';
export const USERS_FACULTY_FETCH_COMPLETED = 'USERS_FACULTY_FETCH_COMPLETED';
export const USERS_FACULTY_FETCH_FAILED = 'USERS_FACULTY_FETCH_FAILED';

export const F_USERS_FACULTY_FETCH_STARTED = 'F_USERS_FACULTY_FETCH_STARTED';
export const F_USERS_FACULTY_FETCH_COMPLETED = 'F_USERS_FACULTY_FETCH_COMPLETED';
export const F_USERS_FACULTY_FETCH_FAILED = 'F_USERS_FACULTY_FETCH_FAILED';

export const M_USERS_FACULTY_FETCH_STARTED = 'M_USERS_FACULTY_FETCH_STARTED';
export const M_USERS_FACULTY_FETCH_COMPLETED = 'M_USERS_FACULTY_FETCH_COMPLETED';
export const M_USERS_FACULTY_FETCH_FAILED = 'M_USERS_FACULTY_FETCH_FAILED';

export const USERS_CAREER_FETCH_STARTED = 'USERS_CAREER_FETCH_STARTED';
export const USERS_CAREER_FETCH_COMPLETED = 'USERS_CAREER_FETCH_COMPLETED';
export const USERS_CAREER_FETCH_FAILED = 'USERS_CAREER_FETCH_FAILED';

export const F_USERS_CAREER_FETCH_STARTED = 'F_USERS_CAREER_FETCH_STARTED';
export const F_USERS_CAREER_FETCH_COMPLETED = 'F_USERS_CAREER_FETCH_COMPLETED';
export const F_USERS_CAREER_FETCH_FAILED = 'F_USERS_CAREER_FETCH_FAILED';

export const M_USERS_CAREER_FETCH_STARTED = 'M_USERS_CAREER_FETCH_STARTED';
export const M_USERS_CAREER_FETCH_COMPLETED = 'M_USERS_CAREER_FETCH_COMPLETED';
export const M_USERS_CAREER_FETCH_FAILED = 'M_USERS_CAREER_FETCH_FAILED';

export const PARTICIPATION_ARTCLUBS_FETCH_STARTED = 'PARTICIPATION_ARTCLUBS_FETCH_STARTED';
export const PARTICIPATION_ARTCLUBS_FETCH_COMPLETED = 'PARTICIPATION_ARTCLUBS_FETCH_COMPLETED';
export const PARTICIPATION_ARTCLUBS_FETCH_FAILED = 'PARTICIPATION_ARTCLUBS_FETCH_FAILED';

export const PARTICIPATION_ARTCLUB_FETCH_STARTED = 'PARTICIPATION_ARTCLUB_FETCH_STARTED';
export const PARTICIPATION_ARTCLUB_FETCH_COMPLETED = 'PARTICIPATION_ARTCLUB_FETCH_COMPLETED';
export const PARTICIPATION_ARTCLUB_FETCH_FAILED = 'PARTICIPATION_ARTCLUB_FETCH_FAILED';

export const PARTICIPATION_ARTCLUB_F_FETCH_STARTED = 'PARTICIPATION_ARTCLUB_F_FETCH_STARTED';
export const PARTICIPATION_ARTCLUB_F_FETCH_COMPLETED = 'PARTICIPATION_ARTCLUB_F_FETCH_COMPLETED';
export const PARTICIPATION_ARTCLUB_F_FETCH_FAILED = 'PARTICIPATION_ARTCLUB_F_FETCH_FAILED';

export const PARTICIPATION_ARTCLUB_M_FETCH_STARTED = 'PARTICIPATION_ARTCLUB_M_FETCH_STARTED';
export const PARTICIPATION_ARTCLUB_M_FETCH_COMPLETED = 'PARTICIPATION_ARTCLUB_M_FETCH_COMPLETED';
export const PARTICIPATION_ARTCLUB_M_FETCH_FAILED = 'PARTICIPATION_ARTCLUB_M_FETCH_FAILED';

export const PARTICIPATION_SPORTCLUBS_FETCH_STARTED = 'PARTICIPATION_SPORTCLUBS_FETCH_STARTED';
export const PARTICIPATION_SPORTCLUBS_FETCH_COMPLETED = 'PARTICIPATION_SPORTCLUBS_FETCH_COMPLETED';
export const PARTICIPATION_SPORTCLUBS_FETCH_FAILED = 'PARTICIPATION_SPORTCLUBS_FETCH_FAILED';

export const PARTICIPATION_SPORTCLUB_FETCH_STARTED = 'PARTICIPATION_SPORTCLUB_FETCH_STARTED';
export const PARTICIPATION_SPORTCLUB_FETCH_COMPLETED = 'PARTICIPATION_SPORTCLUB_FETCH_COMPLETED';
export const PARTICIPATION_SPORTCLUB_FETCH_FAILED = 'PARTICIPATION_SPORTCLUB_FETCH_FAILED';

export const PARTICIPATION_SPORTCLUB_F_FETCH_STARTED = 'PARTICIPATION_SPORTCLUB_F_FETCH_STARTED';
export const PARTICIPATION_SPORTCLUB_F_FETCH_COMPLETED = 'PARTICIPATION_SPORTCLUB_F_FETCH_COMPLETED';
export const PARTICIPATION_SPORTCLUB_F_FETCH_FAILED = 'PARTICIPATION_SPORTCLUB_F_FETCH_FAILED';

export const PARTICIPATION_SPORTCLUB_M_FETCH_STARTED = 'PARTICIPATION_SPORTCLUB_M_FETCH_STARTED';
export const PARTICIPATION_SPORTCLUB_M_FETCH_COMPLETED = 'PARTICIPATION_SPORTCLUB_M_FETCH_COMPLETED';
export const PARTICIPATION_SPORTCLUB_M_FETCH_FAILED = 'PARTICIPATION_SPORTCLUB_M_FETCH_FAILED';

export const PARTICIPATION_ACADEMICCLUBS_FETCH_STARTED = 'PARTICIPATION_ACADEMICCLUBS_FETCH_STARTED';
export const PARTICIPATION_ACADEMICCLUBS_FETCH_COMPLETED = 'PARTICIPATION_ACADEMICCLUBS_FETCH_COMPLETED';
export const PARTICIPATION_ACADEMICCLUBS_FETCH_FAILED = 'PARTICIPATION_ACADEMICCLUBS_FETCH_FAILED';

export const PARTICIPATION_ACADEMICCLUB_FETCH_STARTED = 'PARTICIPATION_ACADEMICCLUB_FETCH_STARTED';
export const PARTICIPATION_ACADEMICCLUB_FETCH_COMPLETED = 'PARTICIPATION_ACADEMICCLUB_FETCH_COMPLETED';
export const PARTICIPATION_ACADEMICCLUB_FETCH_FAILED = 'PARTICIPATION_ACADEMICCLUB_FETCH_FAILED';

export const PARTICIPATION_ACADEMICCLUB_F_FETCH_STARTED = 'PARTICIPATION_ACADEMICCLUB_F_FETCH_STARTED';
export const PARTICIPATION_ACADEMICCLUB_F_FETCH_COMPLETED = 'PARTICIPATION_ACADEMICCLUB_F_FETCH_COMPLETED';
export const PARTICIPATION_ACADEMICCLUB_F_FETCH_FAILED = 'PARTICIPATION_ACADEMICCLUB_F_FETCH_FAILED';

export const PARTICIPATION_ACADEMICCLUB_M_FETCH_STARTED = 'PARTICIPATION_ACADEMICCLUB_M_FETCH_STARTED';
export const PARTICIPATION_ACADEMICCLUB_M_FETCH_COMPLETED = 'PARTICIPATION_ACADEMICCLUB_M_FETCH_COMPLETED';
export const PARTICIPATION_ACADEMICCLUB_M_FETCH_FAILED = 'PARTICIPATION_ACADEMICCLUB_M_FETCH_FAILED';

export const PARTICIPATION_AGRUPATIONS_FETCH_STARTED = 'PARTICIPATION_AGRUPATIONS_FETCH_STARTED';
export const PARTICIPATION_AGRUPATIONS_FETCH_COMPLETED = 'PARTICIPATION_AGRUPATIONS_FETCH_COMPLETED';
export const PARTICIPATION_AGRUPATIONS_FETCH_FAILED = 'PARTICIPATION_AGRUPATIONS_FETCH_FAILED';

export const PARTICIPATION_AGRUPATION_FETCH_STARTED = 'PARTICIPATION_AGRUPATION_FETCH_STARTED';
export const PARTICIPATION_AGRUPATION_FETCH_COMPLETED = 'PARTICIPATION_AGRUPATION_FETCH_COMPLETED';
export const PARTICIPATION_AGRUPATION_FETCH_FAILED = 'PARTICIPATION_AGRUPATION_FETCH_FAILED';

export const PARTICIPATION_AGRUPATION_F_FETCH_STARTED = 'PARTICIPATION_AGRUPATION_F_FETCH_STARTED';
export const PARTICIPATION_AGRUPATION_F_FETCH_COMPLETED = 'PARTICIPATION_AGRUPATION_F_FETCH_COMPLETED';
export const PARTICIPATION_AGRUPATION_F_FETCH_FAILED = 'PARTICIPATION_AGRUPATION_F_FETCH_FAILED';

export const PARTICIPATION_AGRUPATION_M_FETCH_STARTED = 'PARTICIPATION_AGRUPATION_M_FETCH_STARTED';
export const PARTICIPATION_AGRUPATION_M_FETCH_COMPLETED = 'PARTICIPATION_AGRUPATION_M_FETCH_COMPLETED';
export const PARTICIPATION_AGRUPATION_M_FETCH_FAILED = 'PARTICIPATION_AGRUPATION_M_FETCH_FAILED';


export const PARTICIPATION_ASSOCIATIONS_FETCH_STARTED = 'PARTICIPATION_ASSOCIATIONS_FETCH_STARTED';
export const PARTICIPATION_ASSOCIATIONS_FETCH_COMPLETED = 'PARTICIPATION_ASSOCIATIONS_FETCH_COMPLETED';
export const PARTICIPATION_ASSOCIATIONS_FETCH_FAILED = 'PARTICIPATION_ASSOCIATIONS_FETCH_FAILED';

export const PARTICIPATION_ASSOCIATION_FETCH_STARTED = 'PARTICIPATION_ASSOCIATION_FETCH_STARTED';
export const PARTICIPATION_ASSOCIATION_FETCH_COMPLETED = 'PARTICIPATION_ASSOCIATION_FETCH_COMPLETED';
export const PARTICIPATION_ASSOCIATION_FETCH_FAILED = 'PARTICIPATION_ASSOCIATION_FETCH_FAILED';

export const PARTICIPATION_ASSOCIATION_F_FETCH_STARTED = 'PARTICIPATION_ASSOCIATION_F_FETCH_STARTED';
export const PARTICIPATION_ASSOCIATION_F_FETCH_COMPLETED = 'PARTICIPATION_ASSOCIATION_F_FETCH_COMPLETED';
export const PARTICIPATION_ASSOCIATION_F_FETCH_FAILED = 'PARTICIPATION_ASSOCIATION_F_FETCH_FAILED';

export const PARTICIPATION_ASSOCIATION_M_FETCH_STARTED = 'PARTICIPATION_ASSOCIATION_M_FETCH_STARTED';
export const PARTICIPATION_ASSOCIATION_M_FETCH_COMPLETED = 'PARTICIPATION_ASSOCIATION_M_FETCH_COMPLETED';
export const PARTICIPATION_ASSOCIATION_M_FETCH_FAILED = 'PARTICIPATION_ASSOCIATION_M_FETCH_FAILED';