
export const TALLERES_FETCH_STARTED = 'TALLERES_FETCH_STARTED';
export const TALLERES_FETCH_COMPLETED = 'TALLERES_FETCH_COMPLETED';
export const TALLERES_FETCH_FAILED = 'TALLERES_FETCH_FAILED';

export const TALLER_ADD_STARTED = 'TALLER_ADD_STARTED';
export const TALLER_ADD_COMPLETED = 'TALLER_ADD_COMPLETED';
export const TALLER_ADD_FAILED = 'TALLER_ADD_FAILED';

export const TALLER_REMOVE_STARTED = 'TALLER_REMOVE_STARTED';
export const TALLER_REMOVE_COMPLETED = 'TALLER_REMOVE_COMPLETED';
export const TALLER_REMOVE_FAILED = 'TALLER_REMOVE_FAILED';

export const TALLER_UPDATE_STARTED = 'TALLER_UPDATE_STARTED';
export const TALLER_UPDATE_COMPLETED = 'TALLER_UPDATE_COMPLETED';
export const TALLER_UPDATE_FAILED = 'TALLER_UPDATE_FAILED';