export const USERS_BY_EMAIL_FETCH_STARTED = 'USERS_BY_EMAIL_FETCH_STARTED';
export const USERS_BY_EMAIL_FETCH_COMPLETED = 'USERS_BY_EMAIL_FETCH_COMPLETED';
export const USERS_BY_EMAIL_FETCH_FAILED = 'USERS_BY_EMAIL_FETCH_FAILED';